name: Node.js Package

on:
  workflow_dispatch:
    branches: [main]
  release:
    types: [created]

defaults:
  run:
    working-directory: apps/cli/apps/cli

jobs:
  test-on-all-os:
    name: Test on Node ${{ matrix.node }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12.x', '14.x', '16.x']
        os: [ubuntu-latest, windows-2022, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: apps/cli

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Dependency install
        run: yarn

      - name: Test
        run: pnpm test

  publish-npm:
    needs: test-on-all-os
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: apps/cli
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      
      
      - name: Dependency install
        run: yarn
      
      - name: Compile
        run: pnpm build
      
      - name: Publish 
        run: npm publish --access public

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
